# Generated by Django 6.0.2 on 2026-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idutilisateur', models.CharField(db_column='IDUTILISATEUR', max_length=50, primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(blank=True, db_column='Nom_utilisateur', max_length=255, null=True)),
                ('adresse_email', models.EmailField(blank=True, db_column='Adresse_email', max_length=100, null=True)),
                ('mot_de_passe', models.CharField(db_column='Mot_de_passe', max_length=255)),
                ('tel_utilisateur', models.CharField(blank=True, db_column='Tel_utilisateur', max_length=50, null=True)),
                ('role_utilisateur', models.CharField(blank=True, db_column='Role_utilisateur', max_length=50, null=True)),
                ('login_utilisateur', models.CharField(db_column='login_utilisateur', max_length=100, unique=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='date_synchro', null=True)),
                ('effacer', models.BooleanField(default=False)),
                ('sync', models.BooleanField(default=False)),
                ('date_modif', models.DateTimeField(blank=True, null=True)),
                ('date_enreg', models.DateTimeField(blank=True, null=True)),
                ('idutilisateur_save', models.CharField(blank=True, db_column='IDUTILISATEUR_save', max_length=50, null=True)),
                ('codeagence', models.CharField(blank=True, db_column='CodeAgence', max_length=50, null=True)),
                ('est_desactiver', models.BooleanField(default=False)),
                ('daterecupserveur', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
    ]
